name: Generate GitHub Activity

on:
  schedule:
    - cron: '41 7 * * *'  # 7:41 AM UTC (1:10 PM IST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate_activity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate commits
      run: |
        echo "$(date)" >> activity_log.txt
        git config user.name "Pankaj1662005"
        git config user.email "pankajsheokand2005@gmail.com"
        git add .
        git commit -m "Generated commit on $(date)"
        git push
